### ISSUE TITLE
Infografía Ciclo de Vida del Desarrollo de Software 

### ISSUE THREAD

**Issue by Yeim1129** [SistemasTecTlaxiaco/infografia-Yeim1129#2]
José Manuel Hernández Arroyo
https://venngage.net/ps/hIQ2T3OSA/infografa-ciclo-de-vida-del-desarrollo-de-software

**Comment by josealfredo79** [comment]
No hay contenido de la infografia

**Comment by Arnold-Js** [comment]
Califico. Arnol Jesús Cruz Ortiz
Calificación. 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
